[package]
name = "godot_example"
version = "0.1.0"
authors = ["Matthew Collins <thethinkofdeath@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = {git = "https://github.com/Thinkofname/gdnative-rs"}
rand = "0.3"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"